apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc1
  labels:
    app: myapp4
    tier: back-end
spec:
  template:

    metadata:
      name: myapp-pod4
      labels:
        app: myapp4
        tier: back-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
        - name: redis-container
          image: redis

  replicas: 3

  # kuberctl create -f rc-defintion.yml
  # kuberctl get replicationcontroller
  
