apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-con
          image: nginx
  replicas: 4
  selector:
    matchLabels:
      app: myapp

      # to create a replicaset
      -->kubectl create -f filename.yml
      # to list replicaset
      -->kubectl get replicaset
      # to scale the pod
      -->kubectl scale replicaset my-replicaset --replicas=6
