apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    app: testapp
    tier: back-end
spec:
  containers:
    - name: nginx-container
      image: nginx
    - name: redis-container
      image: redis
    - name: jenkins-container
      image: jenkins/jenkins

      #commands to create run sample-pod.yml
      kuberctl create -f sample-pod.yml
      kuberctl get pod
      kuberctl describe pod pod_name
